encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:name>", views.wiki, name="wiki"),
    path("search/", views.search, name="search"),
    path("create/", views.create, name="create"),
    path("edit/<str:name>", views.edit, name="edit"),
    path("random/", views.random, name="random"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django import forms
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponse, request, HttpResponseRedirect
import re
from markdown2 import Markdown
from random import choice

from . import util

class CreatePage(forms.Form):
    new_page = forms.CharField(label="Page Title")
    content = forms.CharField(widget=forms.Textarea)



markdowner = Markdown()

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def wiki(request, name):
        if not util.get_entry(name):
            return render(request, "encyclopedia/404error.html", {
            })
        else:
            page = name
            words = " "
            with open(f"entries/{page}.md", "r") as file:
                lines = file.readlines()
                for line in lines:
                    new_line = markdowner.convert(line)
                    words += new_line
                 
            return render(request, "encyclopedia/wiki.html", {
                    "title": lines[0].replace("#", ""),
                    "content": words
            })
        

def search(request,):
    print(request.GET["q"])
    if util.get_entry(request.GET["q"]):
        page = request.GET["q"]
        words = " "
        with open(f"entries/{page}.md", "r") as file:
            lines = file.readlines()
            for line in lines:
                new_line = markdowner.convert(line)
                words += new_line
                
        return render(request, "encyclopedia/wiki.html", {
                "title": lines[0].replace("#", ""),
                "content": words
        })
    else:
        pages = []
        for entry in util.list_entries():
            if request.GET["q"].lower() in entry.lower():
                pages.append(entry)
        return render(request, "encyclopedia/search-results.html", {
            "pages": pages
        })
              

def create(request):

    if request.method == "POST":
        for page in util.list_entries():
            if request.POST["new_page"].lower() in page.lower():
                return render(request, "encyclopedia/already_exists.html")
                
        util.save_entry(request.POST["new_page"], request.POST["content"])
        return wiki(request, request.POST["new_page"])

    return render(request, "encyclopedia/create.html", {
        "page": CreatePage()
    })


def edit(request, name):

    if request.method == "GET":
        content = util.get_entry(name.strip())
        title = name.strip()
        class EditPage(forms.Form):
            edit = forms.CharField(label="", widget=forms.Textarea, initial=content)
        edits = EditPage()

        return render(request, "encyclopedia/edit.html", {
            #"prefill": content
            "edit": edits,
            "title": title
        })
              
    elif request.method == "POST":
        util.save_entry(name, request.POST["edit"])
        return wiki(request, name)
    

def random(request):
    list = util.list_entries()
    rand = choice(list)
    return wiki(request, rand)
    

encyclopedia/templates/encyclopedia/404error.html
{% extends "encyclopedia/layout.html" %} 

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <h1>404 Error</h1>
    <h2>Page Not Found</h2>

{% endblock %}

encyclopedia/templates/encyclopedia/already_exists.html
{% extends "encyclopedia/layout.html" %} 

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <h1>Cannot Create Page</h1>
    <h2>Page Already Exists!</h2>
    <a href="{% url 'encyclopedia:create' %}">Create Page</a>

{% endblock %}

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %} 

{% block title %}
    Create Page
{% endblock %}

{% block body %}

    <h1>Create Page</h1>
    <form action="{% url 'encyclopedia:create' %}" method="post">
        {% csrf_token %}
        {{ page }}
        <div><input type="submit"></div>

    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %} 

{% block title %}
    Edit Page
{% endblock %}

{% block body %}

    <h1>Edit Page: {{ title }}</h1>
    <form action="{% url 'encyclopedia:edit' title %}" method="post">
        {% csrf_token %}
        {{ edit }}
        <div><input type="submit" value="Save"></div>

    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:wiki' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search-results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results</h1>
    <ul>
        {% for page in pages %} 
        <li><a href="{% url 'encyclopedia:wiki' page %}">{{ page }}</a></li>
        {% empty %} 
        <li>Nothing Found</li>
        {% endfor %} 
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/wiki.html
{% extends "encyclopedia/layout.html" %} 

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}

    {{ content|safe }} 
    <a href="{% url 'encyclopedia:edit' title %}" >Edit Page</a> 

{% endblock %}